version: '3'

#output: group

tasks:
  default:
    - task: isort
    - task: qa

  isort:
    cmds:
      - poetry run isort aoc

  qa:
#    deps: [flake8, pylint, mypy, pytest]
    cmds:
      - defer: { task: pylint }
      - defer: { task: mypy }
      - defer: { task: flake8 }
#    - task: pytest


  mypy:
    cmds:
      - poetry run mypy aoc --implicit-optional

  pylint:
    cmds:
      - poetry run pylint aoc

  flake8:
    cmds:
      - poetry run flake8 aoc

  pytest:
    cmds:
      - poetry run pytest aoc --doctest-modules -vv
